#!/bin/bash
# /usr/bin/blurlock

# take screenshot
import -window root /tmp/screenshot.png

# blur it
convert /tmp/screenshot.png -blur 0x5 /tmp/screenshotblur.png
rm /tmp/screenshot.png

# lock the screen
i3lock -i /tmp/screenshotblur.png

# sleep 1 adds a small delay to prevent possible race conditions with suspend
sleep 1

exit 0


# #!/bin/bash

# # Dependencies:
# # ffmpeg
# # i3lock-color-git

# IMAGE=/tmp/i3lock.png
# TEXT="4iQ"
# SCRIPT=`realpath $0`
# SCRIPTPATH=`dirname $SCRIPT`
# LOCK=$SCRIPTPATH/lock.png
# RES=$(xrandr --current | grep '*' | uniq | awk '{print $1}')
# #This is a bit cheaty
# BOXSIZE=$(expr $(echo $RES | cut -d 'x' -f1) / 2)

# if [[ $1 != "" ]]; then
#     TEXT=$1
# fi

# ffmpeg -f x11grab -video_size $RES -y -i $DISPLAY -i $LOCK -filter_complex "boxblur=5,drawtext=fontfile=$SCRIPTPATH/Digital_tech.otf:text=$TEXT:fontcolor='#ffffffe0':fontsize=40:x=(w-tw)/2:y=(h/PHI)+th:shadowcolor='#1d1f21d0':shadowx=2:shadowy=2:box=1:boxcolor=#1a1b22@0.4:boxborderw=$BOXSIZE,overlay=(main_w-overlay_w)/2:(main_h-overlay_h)/2" -vframes 1 $IMAGE

# i3lock -i $IMAGE

# rm $IMAGE
