# If you come from bash you might have to change your $PATH.
export PATH=$HOME/.bin:/usr/local/bin:/snap/bin/:$PATH
export PATH=$HOME/bin/scripts:$PATH
export PATH=$HOME/bin:$PATH
export PATH=$HOME/.local/bin:$PATH

# This should be done before loading plugins
if [ -d $HOME/bin/fzf/ ]; then
	export FZF_BASE=$HOME/bin/fzf
fi


# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

autoload compinit
compinit
# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="rafaelleru"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in ~/.oh-my-zsh/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS=true

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(docker git fzf vi-mode zsh-autosuggestions taskwarrior)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
 if [[ -n $SSH_CONNECTION ]]; then
   export EDITOR='nvim'
 else
   export EDITOR='nvim'
 fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
#
alias vim="nvim"
alias v="nvim"
alias t="task"
alias nnn="nnn -de"
alias vimconfig="nvim ~/.config/nvim/"
alias i3config="nvim ~/.config/i3/config"
alias dwmconfig="nvim ~/dotfiles/suckless/dwm/config.h"
alias mkdir="mkdir -p"
alias ls="ls --color -lh"
alias cp="cp -R"
alias dps="docker ps | bash $HOME/bin/scripts/alternate_colors.sh"
alias glg="git lg"
alias tmux="tmux -u"
alias py="python3"
alias y="yay"
alias apt="sudo apt"
alias dc="docker-compose"
alias note="nvim ~/notes/$(date +%Y%m%d_%H%M%S).md"
alias cat="batcat"

# run docker exec in a container selected using fzf
function fdex() {
	CONTAINER=`docker ps | rg -v CONTAINER | awk '-F ' ' {print $NF}' | fzf --height 40% --reverse`
	if [ ! -z $CONTAINER ]
	then
		docker exec -it $CONTAINER bash
	fi
}

# run docker logs in a container selected using fzf
function fdlog() {
	CONTAINER=`docker ps | rg -v CONTAINER | awk '-F ' ' {print $NF}' | fzf --height 40% --reverse`
	if [ ! -z $CONTAINER ]
	then
		docker logs -f $CONTAINER
	fi
}



export PATH=$HOME/.bin:$HOME/.bin/scripts:/usr/local/bin:$PATH

if [ -f /usr/share/autojump/autojump.zsh ]; then
	. /usr/share/autojump/autojump.zsh
fi

# This is for debian based installations
if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}"/fzf/fzf.zsh ]; then
	source "${XDG_CONFIG_HOME:-$HOME/.config}"/fzf/fzf.zsh
fi

# This is for arch installations
if [ -f /usr/share/fzf/key-bindings.zsh ]; then
	source /usr/share/fzf/key-bindings.zsh
fi

if [ -f /usr/share/fzf/completions.zsh ]; then
	source /usr/share/fzf/completions.zsh
fi

#Chromium API Keys
export GOOGLE_API_KEY="AIzaSyDUIXvzVrt5OkVsgXhQ6NFfvWlA44by-aw"
export GOOGLE_DEFAULT_CLIENT_ID="449907151817.apps.googleusercontent.com"
export GOOGLE_DEFAULT_CLIENT_SECRET="miEreAep8nuvTdvLums6qyLK"

export MANPAGER='nvim +Man!'

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

source $HOME/.aliases.zsh

# For urlview
export BROWSER='firefox -p constella'

bindkey '^t' autosuggest-accept
bindkey '^f' fzf-file-widget
