local builtin = require('telescope.builtin')
vim.keymap.set('n', '<c-p>', builtin.find_files, { desc = 'Telescope find files' })
vim.keymap.set('n', '<leader>/', builtin.live_grep, { desc = 'Telescope live grep' })
vim.keymap.set('n', '<c-/>', builtin.live_grep, { desc = 'Telescope live grep' })
vim.keymap.set('n', '<c-b>', builtin.buffers, { desc = 'Telescope buffers' })
vim.keymap.set('n', '<leader>w', ":w<CR>")
vim.keymap.set('n', '<leader>x', ":xCR>")
