# file: dotfiles.yml
---
- hosts: all
  become: no
  tasks:

  - name: Install apt packages
    import_tasks: roles/apt.yml
    become: yes
    when: ansible_facts['os_family'] == "Debian"

  - name: Install dnf packages
    import_tasks: roles/dnf.yml
    when: ansible_facts['os_family'] == "RedHat"

  - name: Install pacman packages
    import_tasks: roles/pacman.yml
    when: ansible_facts['os_family'] == "Archlinux"

  - name: Create bin directory in ~
    file:
      path: "{{ lookup('env', 'HOME') }}/bin"
      state: directory

  - name: Create .config directory in ~
    file:
      path: "{{ lookup('env', 'HOME') }}/.config"
      state: directory

  - name: clone my dwm copy
    git:
      repo: https://github.com/rafaelleru/dwm.git
      dest: "{{ lookup('env', 'HOME') }}/bin/dwm"

  - name: Get oh-my-zshrc
    get_url:
      url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
      dest: "/tmp/install-oh-my-zsh.sh"

  - name: Give oh-my-zsh scritp permissions
    shell: "chmod 755 /tmp/install-oh-my-zsh.sh"

  - name: Install oh-my-zshrc
    shell: sh -c /tmp/install-oh-my-zsh.sh --keep-zshrc --unattended

  - name: Install  zsh-autosuggestions
    shell: "git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions"


  - name: Install latest version of neovim
    import_tasks: roles/neovim.yml

  - name: build packages
    import_tasks: roles/build_packages.yml

  - name: create ~/.local/share directory
    file:
      path: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/autoload/"
      state: directory

  - name: install vim plug
    get_url:
      url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
      dest: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/autoload/plug.vim"

  - name: Setup personal dotfiles
    tags: dotfiles
    import_tasks: roles/dotfiles.yml

  - name: links zshrc file in ~ dir
    file:
      src: "{{ lookup('env', 'HOME') }}/dotfiles.bk/config/xsessions/dwm.desktop"
      dest: "/usr/share/xsessions/dwm.desktop"
      state: link
      force: yes
    become: yes


  # TODO: No funciona en la primera instalacion
  #- name: install vim plugins
    #shell: nvim +PlugInstall +q +:q

  #- name: install nvim language servers
    #shell: nvim +LspInstall pylsp gopls clangd dockerls jsonls intelephense vimls +:q

